#!/usr/bin/perl -w

my %friends;

$friends{'Chris'} = 'Rubio';
$friends{'Alec'} = 'Marceles';
$friends{'Sarah'} = 'Fakhoury';

print "Please enter a person name to look up:  \n";
$name = <STDIN>;
chomp($name);

print "The person last name is: $friends{$name} \n";
