#!/usr/bin/perl -w
## Copyright (c) 2017 by yours truly
my $what = 'fred|barney';
my $patt = 'fredbarneybarney';

if ($patt =~ /($what){3}/){
  print "Matched: |$`<$&>$'|\n";
} else {
    print "No match: |$_|\n";
  }
