#!/usr/bin/perl -w

#Open a file subsitute a word and print out to new file

$^I = ".out";
$in = $ARGV[0];
$out = $in.$^I;

open(INFILE,"<$in");
open(OUTFILE1,">$out");

foreach(<INFILE>){
	s/fred|Fred/Larry/g;
	print OUTFILE1  $_;
}

close INFILE;
close OUTFILE1;






