#!/usr/bin/perl -w


$num = int(1 + rand 100);

print "Do you want to turn debug on 1 for yes 2 for no: ";
$debug = <STDIN>;

print "Please guess a number from 1 to 100!";

$count=0;
while (<STDIN>) {


	if ($_ eq "quit\n" || $_ eq "exit\n" || $_ eq "\n"){
                last;
        }elsif ($_ == $num){
                print "You win!\n";
                last;
        }elsif ($_ < $num){
                print "To low! try again: ";
		if ($debug == 1 ){
                         if ($count == 1){
                        print "HINT!!! the number I choose the number $num\n";
			}
		}
        }elsif ($_ > $num){
                print "To high! try again: ";
		if ($debug == 1 ){
			 if ($count == 1){
                        print "HINT!!! the number I choose the number $num\n";
                }
        }
	}
	$count++;
}
